from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    analysis_id: str
    repo_url: str
    repo_path: str
    files_list: List[str]
    tree_structure: Dict[str, Any]
    
    # Reports generated by agents
    tech_stack: Dict[str, Any]
    architecture: Dict[str, Any]
    security: Dict[str, Any]
    code_quality: Dict[str, Any]
    documentation: Dict[str, Any]
    interview_questions: Dict[str, Any]
    
    # Flags/Status
    rag_indexed: bool
    status: str
    error_message: str
